# Redirect root to login page
[[redirects]]
  from = "/"
  to = "/admin-login.html"
  status = 301
  force = true

# Direct /admin to dashboard (client-side auth still enforced)
[[redirects]]
  from = "/admin"
  to = "/admin-dashboard.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Allow Firebase/GSI scripts and network calls
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' https://www.gstatic.com https://apis.google.com 'unsafe-inline'; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https://firestore.googleapis.com https://www.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://www.gstatic.com https://apis.google.com; frame-src 'self' https://accounts.google.com https://apis.google.com;"

# Cache static assets aggressively
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
